/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kurt-howest' at '3/22/18 11:17 AM' with Gradle 2.10
 *
 * @author kurt-howest, @date 3/22/18 11:17 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
